apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: database
spec:
  # Usa o provisionador padrão do Kind para criar a pasta no seu HD
  accessModes:
    - ReadWriteOnce # O disco só pode ser montado por um nó por vez
  resources:
    requests:
      storage: 1Gi    # Pedimos 1 Gigabyte de espaço